// src/types/database.ts
// Auto-generated types for the `listings` table (per user-provided column list).
// - id is optional in Insert (DB uses gen_random_uuid())
// - Arrays use string[]
// - rental_rates: Record<string, unknown> | null
// - All Insert/Update fields optional except id is optional in Insert

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

/** Row type for listings */
export interface ListingsRow {
  id: string;
  owner_id: string | null;
  title: string | null;
  description: string | null;
  address: string | null;
  images: string[] | null;
  video_url: string | null;
  property_type: string | null;
  amenities: string[] | null;
  rules: string[] | null;
  price: number | null;
  beds: number | null;
  baths: number | null;
  square_footage: number | null;
  status: string | null;
  views: number | null;
  likes: number | null;
  contacts: number | null;
  created_at: string | null;
  category: string | null;
  listing_type: string | null;
  city: string | null;
  neighborhood: string | null;
  latitude: number | null;
  longitude: number | null;
  vehicle_brand: string | null;
  vehicle_model: string | null;
  vehicle_condition: string | null;
  year: number | null;
  mileage: number | null;
  engine_cc: number | null;
  fuel_type: string | null;
  transmission_type: string | null;
  color: string | null;
  motorcycle_type: string | null;
  has_abs: boolean | null;
  has_traction_control: boolean | null;
  has_heated_grips: boolean | null;
  has_luggage_rack: boolean | null;
  includes_helmet: boolean | null;
  includes_gear: boolean | null;
  bicycle_type: string | null;
  frame_size: string | null;
  frame_material: string | null;
  number_of_gears: number | null;
  suspension_type: string | null;
  brake_type: string | null;
  wheel_size: number | null;
  electric_assist: boolean | null;
  battery_range: number | null;
  includes_lock: boolean | null;
  includes_lights: boolean | null;
  includes_basket: boolean | null;
  includes_pump: boolean | null;
  service_category: string | null;
  service_type: string | null;
  custom_service_name: string | null;
  work_type: string | null;
  schedule_type: string | null;
  days_available: string[] | null;
  time_slots_available: string[] | null;
  experience_level: string | null;
  experience_years: number | null;
  worker_skills: string[] | null;
  certifications: string[] | null;
  tools_equipment: string[] | null;
  minimum_booking_hours: number | null;
  offers_emergency_service: boolean | null;
  background_check_verified: boolean | null;
  insurance_verified: boolean | null;
  hourly_rate: number | null;
  is_active: boolean | null;
  currency: string | null;
  rental_rates: Record<string, unknown> | null;
  rental_duration_type: string | null;
  pricing_unit: string | null;
  state: string | null;
  country: string | null;
  location_type: string | null;
  service_radius_km: number | null;
  mode: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  furnished: boolean | null;
  pet_friendly: boolean | null;
  house_rules: string[] | null;
  services_included: string[] | null;
}

/** Insert type for listings — id is optional (DB auto-generates) */
export type ListingsInsert = {
  id?: string; // Optional - DB auto-generates
  owner_id?: string | null;
  title?: string | null;
  description?: string | null;
  address?: string | null;
  images?: string[] | null;
  video_url?: string | null;
  property_type?: string | null;
  amenities?: string[] | null;
  rules?: string[] | null;
  price?: number | null;
  beds?: number | null;
  baths?: number | null;
  square_footage?: number | null;
  status?: string | null;
  views?: number | null;
  likes?: number | null;
  contacts?: number | null;
  created_at?: string | null;
  category?: string | null;
  listing_type?: string | null;
  city?: string | null;
  neighborhood?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  vehicle_brand?: string | null;
  vehicle_model?: string | null;
  vehicle_condition?: string | null;
  year?: number | null;
  mileage?: number | null;
  engine_cc?: number | null;
  fuel_type?: string | null;
  transmission_type?: string | null;
  color?: string | null;
  motorcycle_type?: string | null;
  has_abs?: boolean | null;
  has_traction_control?: boolean | null;
  has_heated_grips?: boolean | null;
  has_luggage_rack?: boolean | null;
  includes_helmet?: boolean | null;
  includes_gear?: boolean | null;
  bicycle_type?: string | null;
  frame_size?: string | null;
  frame_material?: string | null;
  number_of_gears?: number | null;
  suspension_type?: string | null;
  brake_type?: string | null;
  wheel_size?: number | null;
  electric_assist?: boolean | null;
  battery_range?: number | null;
  includes_lock?: boolean | null;
  includes_lights?: boolean | null;
  includes_basket?: boolean | null;
  includes_pump?: boolean | null;
  service_category?: string | null;
  service_type?: string | null;
  custom_service_name?: string | null;
  work_type?: string | null;
  schedule_type?: string | null;
  days_available?: string[] | null;
  time_slots_available?: string[] | null;
  experience_level?: string | null;
  experience_years?: number | null;
  worker_skills?: string[] | null;
  certifications?: string[] | null;
  tools_equipment?: string[] | null;
  minimum_booking_hours?: number | null;
  offers_emergency_service?: boolean | null;
  background_check_verified?: boolean | null;
  insurance_verified?: boolean | null;
  hourly_rate?: number | null;
  is_active?: boolean | null;
  currency?: string | null;
  rental_rates?: Record<string, unknown> | null;
  rental_duration_type?: string | null;
  pricing_unit?: string | null;
  state?: string | null;
  country?: string | null;
  location_type?: string | null;
  service_radius_km?: number | null;
  mode?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  furnished?: boolean | null;
  pet_friendly?: boolean | null;
  house_rules?: string[] | null;
  services_included?: string[] | null;
};

/** Update type for listings — all optional */
export type ListingsUpdate = {
  id?: string;
  owner_id?: string | null;
  title?: string | null;
  description?: string | null;
  address?: string | null;
  images?: string[] | null;
  video_url?: string | null;
  property_type?: string | null;
  amenities?: string[] | null;
  rules?: string[] | null;
  price?: number | null;
  beds?: number | null;
  baths?: number | null;
  square_footage?: number | null;
  status?: string | null;
  views?: number | null;
  likes?: number | null;
  contacts?: number | null;
  created_at?: string | null;
  category?: string | null;
  listing_type?: string | null;
  city?: string | null;
  neighborhood?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  vehicle_brand?: string | null;
  vehicle_model?: string | null;
  vehicle_condition?: string | null;
  year?: number | null;
  mileage?: number | null;
  engine_cc?: number | null;
  fuel_type?: string | null;
  transmission_type?: string | null;
  color?: string | null;
  motorcycle_type?: string | null;
  has_abs?: boolean | null;
  has_traction_control?: boolean | null;
  has_heated_grips?: boolean | null;
  has_luggage_rack?: boolean | null;
  includes_helmet?: boolean | null;
  includes_gear?: boolean | null;
  bicycle_type?: string | null;
  frame_size?: string | null;
  frame_material?: string | null;
  number_of_gears?: number | null;
  suspension_type?: string | null;
  brake_type?: string | null;
  wheel_size?: number | null;
  electric_assist?: boolean | null;
  battery_range?: number | null;
  includes_lock?: boolean | null;
  includes_lights?: boolean | null;
  includes_basket?: boolean | null;
  includes_pump?: boolean | null;
  service_category?: string | null;
  service_type?: string | null;
  custom_service_name?: string | null;
  work_type?: string | null;
  schedule_type?: string | null;
  days_available?: string[] | null;
  time_slots_available?: string[] | null;
  experience_level?: string | null;
  experience_years?: number | null;
  worker_skills?: string[] | null;
  certifications?: string[] | null;
  tools_equipment?: string[] | null;
  minimum_booking_hours?: number | null;
  offers_emergency_service?: boolean | null;
  background_check_verified?: boolean | null;
  insurance_verified?: boolean | null;
  hourly_rate?: number | null;
  is_active?: boolean | null;
  currency?: string | null;
  rental_rates?: Record<string, unknown> | null;
  rental_duration_type?: string | null;
  pricing_unit?: string | null;
  state?: string | null;
  country?: string | null;
  location_type?: string | null;
  service_radius_km?: number | null;
  mode?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  furnished?: boolean | null;
  pet_friendly?: boolean | null;
  house_rules?: string[] | null;
  services_included?: string[] | null;
};

/** Database interface in the Supabase expected shape */
export interface Database {
  public: {
    Tables: {
      listings: {
        Row: ListingsRow;
        Insert: ListingsInsert;
        Update: ListingsUpdate;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
}
